<?php

define("TYPE_VID", 3);
define("BRAND_VID", 2);

function product_filter_theme($existing, $type, $theme, $path) {
    $path = drupal_get_path('module', 'product_filter') . '/theme';

    return array(
        'featured_products' => array(
            'arguments' => array(
                'products' => array(),
            ),
            'template' => 'featured_products',
            'path' => $path,
        ),
    );
}

function product_filter_block($op = 'list', $delta = 0, $edit = array()) {
    drupal_add_css(drupal_get_path('module', 'product_filter') . "/css/product_filter.css");

    switch ($op) {
        case 'list':

            $blocks['product_block'] = array(
                'info' => t('Product filter block'),
                'weight' => 0,
            );

            $blocks['product_block_2'] = array(
                'info' => t('Product filter block 2'),
                'weight' => 0,
            );

            $blocks['product_block_featured'] = array(
                'info' => t('Product featured block'),
                'weight' => 0,
            );

            return $blocks;

            break;

        case 'configure' :

            switch ($delta) {

                case 'product_block_featured':

                    $form['product_block_featured_1'] = array(
                        '#type' => 'select',
                        '#title' => t('Featured Product 1'),
                        '#default_value' => variable_get('product_block_featured_1', 0),
                        '#description' => "Select which <em>product</em> will feature as item 1.",
                        '#options' => _product_filter_opts(),
                    );

                    $form['product_block_featured_2'] = array(
                        '#type' => 'select',
                        '#title' => t('Featured Product 2'),
                        '#default_value' => variable_get('product_block_featured_2', 0),
                        '#description' => "Select which <em>product</em> will feature as item 2.",
                        '#options' => _product_filter_opts(),
                    );

                    $form['product_block_featured_3'] = array(
                        '#type' => 'select',
                        '#title' => t('Featured Product 3'),
                        '#default_value' => variable_get('product_block_featured_3', 0),
                        '#description' => "Select which <em>product</em> will feature as item 3.",
                        '#options' => _product_filter_opts(),
                    );

                    return $form;

                    break;
            }

            break;

        case 'save';

            switch ($delta) {

                case 'product_block_featured':

                    variable_set('product_block_featured_1', $edit['product_block_featured_1']);
                    variable_set('product_block_featured_2', $edit['product_block_featured_2']);
                    variable_set('product_block_featured_3', $edit['product_block_featured_3']);

                    break;
            }
            break;


        case 'view':

            switch ($delta) {
                case 'product_block':

                    $block = array(
                        'subject' => t('Product filter block'),
                        'content' => drupal_get_form("product_filter_block_1"),
                    );

                    break;
                
                case 'product_block_2':

                    $block = array(
                        'subject' => t('Product filter block 2'),
                        'content' => drupal_get_form("product_filter_block_3"),
                    );

                    break;

                case 'product_block_featured':

                    $featured = array(
                        variable_get('product_block_featured_1', 0),
                        variable_get('product_block_featured_2', 0),
                        variable_get('product_block_featured_3', 0),
                    );

                    $block = array(
                        'subject' => t('Featured Products'),
                        'content' => product_filter_block_2($featured),
                    );

                    break;
            }

            return $block;

            break;
    }
}

function _product_filter_opts(){

    $products = array();

    $result = db_query("SELECT nid FROM {node} WHERE type = '%s'", "product");

    while ($data = db_fetch_object($result)) {
        $node = node_load($data->nid);

        $products[$node->nid] = $node->title;
    }

    return $products;
}

function _product_filter_brand_opts() {

    $options = array();

    $vocab = taxonomy_get_tree(BRAND_VID);

    foreach($vocab as $term){
        $options[$term->tid] = $term->name;
    }

    return $options;
}

function _product_filter_type_opts() {

    $options = array();

    $vocab = taxonomy_get_tree(TYPE_VID);

    foreach($vocab as $term){
        $options[$term->tid] = $term->name;
    }

    return $options;
}

function product_filter_block_1($form) {

    $form['title'] = array(
        '#type' => 'textfield',
        '#title' => t('Product name'),
        '#size' => 60,
        '#maxlength' => 128,
        '#required' => TRUE,
    );

    $form['submit'] = array('#type' => 'submit', '#value' => t('Search'));

    return $form;
}

function product_filter_block_2($featured = array()) {
    $products = array();

    foreach($featured as $nid){
        $node = node_load($nid);
        $products[] = array(
            'image' => theme('imagecache', 'product-thumbnail', $node->field_image[0]['filepath']),
            'title' => $node->title,
            'price' => "&pound" . number_format($node->field_price[0]['value'],2),
            'path' => "node/{$node->nid}",
        );
    }
    
    return theme("featured_products", $products);
}

function product_filter_block_3($form) {

    $form['brand'] = array(
        '#type' => 'select',
        '#title' => t('Brand'),
        '#options' => _product_filter_brand_opts(),
    );

    $form['type'] = array(
        '#type' => 'select',
        '#title' => t('Type'),
        '#options' => _product_filter_type_opts(),
    );

    $form['submit'] = array('#type' => 'submit', '#value' => t('Search'));

    return $form;
}